spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${ET_DB_NAME}?currentSchema=${ET_SCHEMA_NAME}
    username: ${ET_DB_API_USER}
    password: ${ET_DB_API_PWD}
  liquibase:
    user: ${ET_DB_DBO_USER}
    password: ${ET_DB_DBO_PWD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/${KC_REALM}
  jpa:
    show-sql: true
springdoc:
  swagger-ui:
    oauth:
      client-id: ${KC_CLIENT_ID}
      client-secret: ${KC_CLIENT_SECRET}
      realm: ${KC_REALM}
      scopes: openid,profile,email,roles
      token-url: http://localhost:8080/realms/${KC_REALM}/protocol/openid-connect/token
      use-pkce-with-authorization-code-grant: false
      additional-query-string-params:
        client_id: ${KC_CLIENT_ID}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.web.security: DEBUG
    com.nimbusds.jwt: DEBUG
    com.nimbusds.jose: DEBUG
    org.springframework.web: DEBUG
    org.apache.http: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE