name: Build, Test & Deploy to Heroku

on:
  push:
    branches: [ "main" ]
jobs:
  builds-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '24'
          distribution: 'temurin'
        
      - name: Build with Gradle
        working-directory: ./expensetracker
        run: |
          gradle build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./expensetracker/build/reports/jacoco/html/
